#!/usr/bin/with-contenv bash

echo '
******************************************************
******************************************************
*                                                    *
*                                                    *
*            This image is not supported.            *
*                                                    *
*                                                    *
*                                                    *
******************************************************
******************************************************

nzbget has been deprecated by its developers. Please consider switching to SABnzbd https://github.com/linuxserver/docker-sabnzbd if you need support
Attempts to update with nzbget-ng development will happen as time allows

******************************************************
******************************************************'
